volumes:
  pg:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: ./backend/
    volumes:
      - static:/backend_static/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    env_file:
      - .env

  gateway:
    build: ./infra/
    ports:
      - "9090:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
      - db
